<?xml version="1.0" encoding="utf-8"?><Database Name="SP_SE" Class="SP_SEDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=GEORGEMAIN;Initial Catalog=SP_SE;Integrated Security=True" SettingsObjectName="SE_Repository.Properties.Settings" SettingsPropertyName="SP_SEConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Content" Member="Contents">
    <Type Name="Content">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Url" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>